[tool.mypy]
strict = true
[[tool.mypy.overrides]]
module = [
    "numpy.*"
]
strict=false
disallow_untyped_calls = false
disallow_untyped_defs = false

[tool.black]
line-length = 120
target-version = ['py38']
skip-string-normalization = true

[tool.isort]
line_length = 120
multi_line_output = 5
profile = "black"


[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
precision = 1
fail_under = 90